using System.Text;
using System.Text.Json;
using SowSiege.Core;

namespace SowSiege.Sim;

public static partial class UnityExport
{
    public const string ProfileName = "production";

    public static string Generate(string directory, string profileName = ProfileName)
    {
        var snapshot = UnityExportSnapshot.Capture(directory);
        var catalog = ContentLoader.Load(directory, false, profileName);
        var presentation = UnityExportPresentation.Load(directory);
        var profileHash = ContentLoader.ProfileHash(directory, profileName);
        var source = new StringBuilder("// Generated by tools/prepare-unity.sh from canonical data. Do not edit.\n#nullable disable\nnamespace Game.App.Generated\n{\n");
        source.AppendLine("    public readonly struct BundleFile { public string RelativePath { get; } public long ByteLength { get; } public string Sha256 { get; } public BundleFile(string path, long length, string hash) { RelativePath = path; ByteLength = length; Sha256 = hash; } }");
        source.AppendLine("    public readonly struct ContentDisplay { public string Id { get; } public string DisplayName { get; } public string Category { get; } public string EffectDescription { get; } public string GrowthDescription { get; } public string EvolutionHint { get; } public ContentDisplay(string id, string name, string category, string effect, string growth, string evolution) { Id = id; DisplayName = name; Category = category; EffectDescription = effect; GrowthDescription = growth; EvolutionHint = evolution; } }");
        source.AppendLine("    public readonly struct CameraSettings { public int WorldUnitsPerUnityUnit { get; } public int MinHalfHeight { get; } public int MaxHalfHeight { get; } public int EstatePadding { get; } public int FollowMilliseconds { get; } public int ZoomMilliseconds { get; } public CameraSettings(int units, int min, int max, int padding, int follow, int zoom) { WorldUnitsPerUnityUnit = units; MinHalfHeight = min; MaxHalfHeight = max; EstatePadding = padding; FollowMilliseconds = follow; ZoomMilliseconds = zoom; } }");
        source.AppendLine("    public readonly struct PresentationSettings { public CameraSettings Camera { get; } public PresentationSettings(CameraSettings camera) { Camera = camera; } }");
        source.AppendLine("    public readonly struct UpgradeStat { public string Id { get; } public string Label { get; } public string Unit { get; } public int Level { get; } public int Value { get; } public bool PerLevel { get; } public UpgradeStat(string id, string label, string unit, int level, int value, bool perLevel) { Id = id; Label = label; Unit = unit; Level = level; Value = value; PerLevel = perLevel; } }");
        source.AppendLine("    public static class CanonicalContent\n    {");
        source.AppendLine($"        public const string ProfileName = {Literal(profileName)};");
        source.AppendLine($"        public const string ProfileHash = {Literal(profileHash)};");
        source.AppendLine($"        public const string DataHash = {Literal(snapshot.DataHash)};");
        var camera = presentation.Camera;
        source.AppendLine(FormattableString.Invariant($"        public static readonly PresentationSettings Presentation = new PresentationSettings(new CameraSettings({camera.WorldUnitsPerUnityUnit}, {camera.MinHalfHeight}, {camera.MaxHalfHeight}, {camera.EstatePadding}, {camera.FollowMilliseconds}, {camera.ZoomMilliseconds}));"));
        source.AppendLine("        public static readonly BundleFile[] Files = new BundleFile[] {");
        foreach (var file in snapshot.Files)
        {
            source.AppendLine(FormattableString.Invariant($"            new BundleFile({Literal(file.RelativePath)}, {file.ByteLength}L, {Literal(file.Sha256)}),"));
        }
        source.AppendLine("        };\n        public static readonly ContentDisplay[] Displays = new ContentDisplay[] {");
        var displays = Displays(directory, snapshot, catalog).ToArray();
        var names = displays.ToDictionary(display => display.Id, display => display.Name, StringComparer.Ordinal);
        foreach (var display in displays)
        {
            source.AppendLine($"            new ContentDisplay({Literal(display.Id)}, {Literal(display.Name)}, {Literal(display.Category)}, {Literal(DisplayDescription(catalog, display.Id, names))}, {Literal(GrowthDescription(catalog, display.Id, names))}, {Literal(EvolutionHint(directory, catalog, display.Id))}),");
        }
        source.AppendLine("        };");
        source.AppendLine("        public static readonly UpgradeStat[] UpgradeStats = new UpgradeStat[] {");
        foreach (var stat in UpgradeStats(catalog)) { source.AppendLine(FormattableString.Invariant($"            new UpgradeStat({Literal(stat.Id)}, {Literal(stat.Label)}, {Literal(stat.Unit)}, {stat.Level}, {stat.Value}, {stat.PerLevel.ToString().ToLowerInvariant()}),")); }
        source.AppendLine("        };");
        source.AppendLine("        public static global::SowSiege.Core.ContentCatalog CreateCatalog() => " + UnityExportExpression.Write(catalog) + ";");
        source.AppendLine("    }\n}");
        snapshot.AssertUnchanged(directory);
        return source.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    public static void Write(string directory, string output, string profileName = ProfileName)
    {
        var source = Generate(directory, profileName);
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
        File.WriteAllText(output, source, new UTF8Encoding(false));
    }

    public static void Verify(string directory, string output, string profileName = ProfileName)
    {
        if (!File.Exists(output) || File.ReadAllText(output) != Generate(directory, profileName))
        {
            throw new InvalidDataException("Stale Unity canonical bridge; run tools/prepare-unity.sh.");
        }
    }

    private static string Literal(string value) => JsonSerializer.Serialize(value);

    private static IEnumerable<(string Id, string Name, string Category)> Displays(string directory, UnityExportSnapshot snapshot, ContentCatalog catalog)
    {
        var selected = catalog.Tools.Keys.Concat(catalog.Weapons.Keys).Concat(catalog.Heroes.Keys).Concat(catalog.Estates.Keys).Concat(catalog.Enemies.Keys)
            .Concat(catalog.Runtime!.Charters.Keys).Concat(catalog.Runtime.Items.Keys).Concat(catalog.Runtime.Evolutions.Keys).ToHashSet(StringComparer.Ordinal);
        foreach (var file in snapshot.Files)
        {
            var kind = file.RelativePath.Split('/')[0];
            if (kind is not ("tools" or "weapons" or "heroes" or "estates" or "enemies" or "charters" or "items" or "evolutions")) { continue; }
            using var json = JsonDocument.Parse(File.ReadAllBytes(Path.Combine(directory, file.RelativePath)));
            var record = json.RootElement;
            var id = record.GetProperty("id").GetString()!;
            if (!selected.Remove(id)) { continue; }
            var category = kind switch
            {
                "tools" => catalog.Tools[id].Growth.Target,
                "weapons" => "weapon",
                "charters" => catalog.Runtime.Charters[id].PolicyCategory,
                "heroes" => "hero",
                "estates" => "estate",
                "enemies" => "enemy",
                "items" => "item",
                "evolutions" => "evolution",
                _ => throw new InvalidDataException("Unsupported display kind.")
            };
            yield return (id, record.GetProperty("name").GetString() ?? throw new InvalidDataException("Missing display name."), category);
        }
        if (selected.Count != 0) { throw new InvalidDataException("Missing selected canonical display records."); }
    }
}
