import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { canonical } from './s4b-contract.mjs';
import { formatCsv } from './csv.mjs';
import { makeCases,pairedEffects,firstDivergence,selectPublicCases,summarizePaired } from './diagnostic-analysis.mjs';
import { validatePacket } from './diagnostic-packet.mjs';
const identity=r=>({caseId:r.caseId,cohort:r.cohort,policy:r.policy,peopleRule:r.peopleRule,seed:r.seed,arm:r.arm});
export const numeric=(obj,prefix='',out={})=>{for(const[k,v]of Object.entries(obj)){if(k==='interceptedTargetKinds')continue;const name=prefix?`${prefix}_${k}`:k;if(typeof v==='number')out[name]=v;else if(v&&typeof v==='object'&&!Array.isArray(v))numeric(v,name,out);}return out;};
const metrics=s=>({...numeric(s),weaponCount:s.equipment.filter(e=>e.kind==='weapon').length,weaponRankSum:s.equipment.filter(e=>e.kind==='weapon').reduce((a,e)=>a+e.rank,0),peopleEntities:s.population.reduce((a,p)=>a+p.entities,0),peopleMembers:s.population.reduce((a,p)=>a+p.members,0),peopleMemberTicks:s.population.reduce((a,p)=>a+p.memberTicks,0),personAppliedDamage:s.attackSources.filter(a=>a.actorKind==='person').reduce((a,p)=>a+p.appliedHpDamage,0),buildingAppliedDamage:s.attackSources.filter(a=>a.actorKind==='building').reduce((a,p)=>a+p.appliedHpDamage,0)});
export function commonAliveSnapshots(controlSnapshots,treatmentSnapshots){
  const alive=s=>!(s.terminal&&s.survived===false);
  const treatmentByTick=new Map(treatmentSnapshots.filter(alive).map(s=>[s.tick,s]));
  const control=controlSnapshots.filter(s=>alive(s)&&treatmentByTick.has(s.tick)).at(-1);
  assert.ok(control,'no shared alive snapshot');
  return {control,treatment:treatmentByTick.get(control.tick)};
}
export async function writeAnalysis(rows,output,mode){
  const expected=makeCases(mode);assert.deepEqual(rows.map(r=>r.caseId).sort(),expected.map(r=>r.caseId).sort(),'exact case matrix required');const byId=new Map(rows.map(r=>[r.caseId,r]));
  const {pairs,interactions}=pairedEffects(rows);
  const runRows=rows.map(r=>{const control=byId.get(r.caseId.replace(/__(control|offense-off|interception-off|both-off)$/,'__control'));let firstSampledTelemetryDivergenceTick=null;
    for(const s of r.packet.diagnostics.snapshots){const c=control.packet.diagnostics.snapshots.find(c=>c.tick===s.tick);if(c&&canonical(c)!==canonical(s)){firstSampledTelemetryDivergenceTick=s.tick;break;}}
    return {...identity(r),...r.packet.outcome,gameplayHash:r.gameplayHash,gameplayDigest:r.gameplayDigest,diagnosticDigest:r.diagnosticDigest,diagnosticIdentity:r.diagnosticIdentity,firstRngDivergenceTick:firstDivergence(control.rng,r.rng),firstSampledTelemetryDivergenceTick,requestedEndTick:r.requestedTicks,censorKind:r.survived?'duration':'death'};});
  const common=pairs.map(p=>{const c=byId.get(p.controlCaseId),t=byId.get(p.treatmentCaseId),shared=commonAliveSnapshots(c.packet.diagnostics.snapshots,t.packet.diagnostics.snapshots),tick=shared.control.tick;const cm=metrics(shared.control),tm=metrics(shared.treatment);return {...p,commonObservedTick:tick,personDamageDifference:tm.personAppliedDamage-cm.personAppliedDamage,personDamagePerSecondDifference:tick?(tm.personAppliedDamage-cm.personAppliedDamage)/(tick/30):null,interceptDifference:tm.interception_interceptCount-cm.interception_interceptCount,workerTicksDifference:tm.growth_workerTicks-cm.growth_workerTicks,admittedHpDifference:tm.threat_admittedHp-cm.threat_admittedHp};});
  const summaries=[...summarizePaired(pairs,'survivalDifference',['policy','peopleRule','arm']),...summarizePaired(pairs,'restrictedTicksDifference',['policy','peopleRule','arm']),...summarizePaired(interactions,'ticksInteraction',['policy','peopleRule']),...summarizePaired(interactions,'survivalInteraction',['policy','peopleRule'])].map(r=>({policy:r.policy,peopleRule:r.peopleRule,arm:r.arm??'factorial',metric:r.metric,nSeedBlocks:r.nSeedBlocks,mean:r.mean,standardError:r.standardError,intervalDefinition:r.intervalDefinition,lower:r.lower,upper:r.upper}));
  const policyDifference=[];for(const p of pairs.filter(p=>p.policy==='people')){const w=pairs.find(w=>w.policy==='weapon'&&w.peopleRule===p.peopleRule&&w.seed===p.seed&&w.arm===p.arm);assert.ok(w);policyDifference.push({peopleRule:p.peopleRule,seed:p.seed,arm:p.arm,peopleMinusWeaponSurvivalEffect:p.survivalDifference-w.survivalDifference,peopleMinusWeaponTicksEffect:p.restrictedTicksDifference-w.restrictedTicksDifference});}
  const snapshots=[];const groups=new Map();for(const r of rows){const key=[r.cohort,r.policy,r.peopleRule,r.arm].join('/');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}
  for(const g of groups.values())for(let tick=0;tick<=g[0].requestedTicks;tick+=300){const observed=g.flatMap(r=>r.packet.diagnostics.snapshots.filter(s=>s.tick===tick).map(s=>({r,s}))),alive=observed.filter(x=>!x.s.terminal||x.s.survived),keys=[...new Set(alive.flatMap(x=>Object.keys(metrics(x.s))))].filter(k=>k!=='tick').sort();const sums={};for(const k of keys)sums[k]=alive.reduce((a,x)=>a+(metrics(x.s)[k]??0),0);snapshots.push({cohort:g[0].cohort,policy:g[0].policy,peopleRule:g[0].peopleRule,arm:g[0].arm,tick,requestedEndTick:g[0].requestedTicks,nCases:g.length,nAlive:alive.length,nDead:g.filter(r=>!r.survived&&r.ticks<=tick).length,nAtRisk:g.filter(r=>r.ticks>=tick).length,nObserved:observed.length,aliveSumsJson:canonical(sums),denominator:'regular300tick grid only; actual off-grid terminal in terminal-counters.csv; nAlive; sum of actual surviving snapshots only; no postdeath carryforward'});}
  const attacks=[],population=[],equipment=[],terminalCounters=[],cards=[];for(const r of rows){const end=r.packet.diagnostics.snapshots.at(-1);terminalCounters.push({...identity(r),...metrics(end),targetDamageJson:canonical(end.targetDamage),interceptedTargetKindsJson:canonical(end.interception.interceptedTargetKinds)});for(const card of r.packet.cards)cards.push({...identity(r),tick:card.tick,level:card.level,chosen:card.chosen,rarity:card.rarity,offeredJson:canonical(card.offered)});for(const a of r.packet.diagnostics.attackSources)attacks.push({...identity(r),observedTicks:r.ticks,...a});for(const p of end.population)population.push({...identity(r),observedTicks:r.ticks,...p});for(const e of end.equipment)equipment.push({...identity(r),...e,weaponSlots:end.weaponSlots,toolSlots:end.toolSlots,charterSlots:end.charterSlots});}
  const provenance=rows.map(r=>({...identity(r),packetFile:`packets/${r.caseId}.json`,packetSha256:r.packetSha256,commit:r.packet.provenance.commit,gitDirty:r.packet.provenance.gitDirty,inputHash:r.packet.provenance.inputHash,contentSha256:r.packet.provenance.contentSha256,profileSha256:r.packet.provenance.profileSha256,tuningSha256:r.packet.provenance.tuningSha256,sourceTreeSha256:r.packet.provenance.sourceTreeSha256,coreAssemblySha256:r.packet.provenance.coreAssemblySha256,simulationAssemblySha256:r.packet.provenance.simulationAssemblySha256}));
  const tables={'runs.csv':runRows,'terminal-counters.csv':terminalCounters,'card-choices.csv':cards,'paired.csv':common,'interactions.csv':interactions,'paired-summary.csv':summaries,'policy-effect-differences.csv':policyDifference,'snapshots.csv':snapshots,'attack-sources.csv':attacks,'population.csv':population,'equipment.csv':equipment,'provenance.csv':provenance,'public-selection.csv':mode==='full'?selectPublicCases(rows):[]};
  for(const[name,table]of Object.entries(tables))await fs.writeFile(path.join(output,name),formatCsv(table.length?Object.keys(table[0]):['caseId','reason','controlCaseId'],table));
  return tables;
}
export async function replay(input,output,mode){await fs.mkdir(output);const cases=makeCases(mode),files=(await fs.readdir(path.join(input,'packets'))).filter(f=>f.endsWith('.json'));assert.deepEqual(files.sort(),cases.map(c=>`${c.caseId}.json`).sort());const rows=[];for(const c of cases){const bytes=await fs.readFile(path.join(input,'packets',`${c.caseId}.json`));rows.push({...validatePacket(JSON.parse(bytes),c),packetSha256:createHash('sha256').update(bytes).digest('hex')});}return writeAnalysis(rows,output,mode);}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))replay(process.argv[2],process.argv[3],process.argv[4]??'full').catch(e=>{console.error(e.message);process.exitCode=1;});
