import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { formatCsv } from './csv.mjs';
import { load } from './s4b-input.mjs';
import { POLICIES, RULES, canonical, totalDamage, requireValue } from './s4b-contract.mjs';
export const median=values=>{if(!values.length)return null;const s=[...values].sort((a,b)=>a-b),i=Math.floor(s.length/2);return s.length%2?s[i]:(s[i-1]+s[i])/2;};
export const percentile=(values,p)=>values.length?[...values].sort((a,b)=>a-b)[Math.max(0,Math.ceil(values.length*p)-1)]:null;
const sum=(rows,fn)=>rows.reduce((n,r)=>n+fn(r),0);
const mean=values=>values.length?sum(values,x=>x)/values.length:null;
export function wilson(successes,n){if(!n)return{low:null,high:null};const z=1.959963984540054,p=successes/n,d=1+z*z/n,center=(p+z*z/(2*n))/d,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return{low:Math.max(0,center-half),high:Math.min(1,center+half)};}
export const rankTuple=r=>[Number(r.survived),r.ticks,r.level,totalDamage(r)];
const compare=(a,b)=>{for(let i=0;i<a.length;i++)if(a[i]!==b[i])return a[i]>b[i]?1:-1;return 0;};
const winners=(rows,tuple)=>{let best=null,result=[];for(const row of rows){const current=tuple(row),order=best===null?1:compare(current,best);if(order>0){best=current;result=[row];}else if(order===0)result.push(row);}return result;};
export function summarize(league){
  const{data,configuration:c,metadata}=league,runs=data.runs;
  const outcomes=[],xp=[],distance=[],waits=[],deaths=[];
  for(const policy of c.policies)for(const rule of c.rules)for(const movementMode of c.movements){
    const group=runs.filter(r=>r.policy===policy&&r.peopleRule===rule&&r.caseId.endsWith('__'+movementMode));
    const survived=group.filter(r=>r.survived&&r.ticks===21600),key={policy,peopleRule:rule,movementMode},levels=group.map(r=>r.level),survivorLevels=survived.map(r=>r.level),n=group.length;
    outcomes.push({...key,caseCount:n,seedBlockCount:n,survived:survived.length,survivalRate:survived.length/n,truncatedAlive:group.filter(r=>r.survived&&r.ticks<21600).length,meanReachedSeconds:mean(group.map(r=>r.ticks/30)),meanLevel:mean(levels),meanCombatDamage:mean(group.map(totalDamage))});
    const survivorMedian=median(survivorLevels);xp.push({...key,caseCount:n,allFinalLevelMedian:median(levels),allFinalLevelMin:Math.min(...levels),allFinalLevelMax:Math.max(...levels),fullDurationSurvivors:survived.length,survivorLevelMin:survivorLevels.length?Math.min(...survivorLevels):null,survivorLevelMedian:survivorMedian,survivorLevelMax:survivorLevels.length?Math.max(...survivorLevels):null,targetPass:survivorMedian!==null&&survivorMedian>=25&&survivorMedian<=45});
    const caseIds=new Set(group.map(r=>r.caseId)),samples=data['movement-samples'].filter(r=>caseIds.has(r.caseId)),distances=samples.map(r=>Math.sqrt(r.distanceSquared));
    distance.push({...key,unit:metadata.experimentJson.worldUnit,caseCount:n,sampleCount:distances.length,median:median(distances),p95:percentile(distances,.95),min:distances.length?Math.min(...distances):null,max:distances.length?Math.max(...distances):null,under500:distances.filter(x=>x<500).length,from500To1499:distances.filter(x=>x>=500&&x<1500).length,from1500To2999:distances.filter(x=>x>=1500&&x<3000).length,atLeast3000:distances.filter(x=>x>=3000).length});
    for(const endKind of ['harvest','destroyed','death-censored','duration-censored']){const events=data['farm-wait-events'].filter(r=>caseIds.has(r.caseId)&&r.endKind===endKind),seconds=events.map(r=>r.observedWaitTicks/30);waits.push({...key,endKind,interpretation:endKind==='harvest'?'completed-harvest':endKind==='destroyed'?'competing-destruction':'right-censored-lower-bound',events:events.length,meanSeconds:mean(seconds),medianSeconds:median(seconds),p95Seconds:percentile(seconds,.95)});}
    const dead=group.filter(r=>!r.survived),seconds=dead.map(r=>r.ticks/30);deaths.push({...key,caseCount:n,deaths:dead.length,fullDurationCensored:survived.length,truncatedAlive:group.filter(r=>r.survived&&r.ticks<21600).length,deathTimeMinSeconds:seconds.length?Math.min(...seconds):null,deathTimeMedianSeconds:median(seconds),deathTimeP95Seconds:percentile(seconds,.95),before180:seconds.filter(x=>x<180).length,from180To359:seconds.filter(x=>x>=180&&x<360).length,from360To539:seconds.filter(x=>x>=360&&x<540).length,atLeast540:seconds.filter(x=>x>=540).length});
  }
  const conditions=[],groupRanks=[],pairs=[];let dominant=[];
  if(c.experiment==='A'){
    dominant=[...POLICIES];
    for(const peopleRule of RULES)for(const seed of c.seeds){const group=runs.filter(r=>r.peopleRule===peopleRule&&r.seed===seed),first=winners(group,rankTuple).map(r=>r.policy);dominant=dominant.filter(p=>first.includes(p));conditions.push({peopleRule,seed,cofirstPoliciesJson:JSON.stringify(first)});
      const ledger=policy=>data.cards.filter(r=>r.caseId===`${policy}__${peopleRule}__${seed}__circuit`).map(({choiceIndex,tick,level,offeredIdsJson,chosenId,rarity})=>({choiceIndex,tick,level,offeredIdsJson,chosenId,rarity}));pairs.push({peopleRule,seed,identical:canonical(ledger('mixed'))===canonical(ledger('random')),mixedChoices:ledger('mixed').length,randomChoices:ledger('random').length});}
    for(const peopleRule of RULES){const groups=POLICIES.map(policy=>({policy,runs:runs.filter(r=>r.peopleRule===peopleRule&&r.policy===policy)}));const tuple=g=>[sum(g.runs,r=>Number(r.survived)),sum(g.runs,r=>r.ticks),sum(g.runs,r=>r.level),sum(g.runs,totalDamage)];const first=winners(groups,tuple).map(g=>g.policy);for(const g of groups){const totals=tuple(g);groupRanks.push({peopleRule,policy:g.policy,caseCount:g.runs.length,survived:totals[0],ticksSum:totals[1],levelSum:totals[2],combatDamageSum:totals[3],cofirst:first.includes(g.policy)});}}
  }
  const baseline=runs.filter(r=>r.policy==='random'&&r.peopleRule==='C'&&r.caseId.endsWith('__circuit')),successes=baseline.filter(r=>r.survived&&r.ticks===21600).length,interval=wilson(successes,baseline.length);
  const baselineSummary={cases:baseline.length,fullDurationAssessed:!c.smoke,survived:c.smoke?null:successes,survivalRate:c.smoke?null:baseline.length?successes/baseline.length:null,wilson95Low:c.smoke?null:interval.low,wilson95High:c.smoke?null:interval.high,deaths:baseline.filter(r=>!r.survived).length,truncatedAlive:baseline.filter(r=>r.survived&&r.ticks<21600).length};
  const movementPass=data['movement-equality'].every(r=>r.mismatchCount===0),mixedPass=pairs.every(r=>!r.identical),xpPass=xp.every(r=>r.targetPass);
  const validity=movementPass&&(c.experiment!=='A'||c.smoke||mixedPass);
  const gates=[{gate:'validity',pass:validity,applicable:true},{gate:'a',pass:baselineSummary.survivalRate>=.3&&baselineSummary.survivalRate<=.7,applicable:c.experiment==='A'&&!c.smoke},{gate:'b',pass:dominant.length===0,applicable:c.experiment==='A'&&!c.smoke},{gate:'c',pass:['weapon','land','building','people'].every(policy=>groupRanks.some(r=>r.policy===policy&&r.cofirst)),applicable:c.experiment==='A'&&!c.smoke},{gate:'d',pass:true,applicable:c.experiment==='A'&&!c.smoke},{gate:'XP',pass:xpPass,applicable:c.experiment==='A'&&!c.smoke},{gate:'mixed-ledger',pass:mixedPass,applicable:c.experiment==='A'&&!c.smoke}];
  const overall=!validity?'INVALID':c.smoke?'SMOKE_ONLY':c.experiment==='A'?(gates.filter(g=>g.applicable).every(g=>g.pass)?'PASS':'FAIL'):c.experiment==='calibration'?(baselineSummary.survivalRate>=.3&&baselineSummary.survivalRate<=.7&&xpPass?'QUALIFIED':'NOT_QUALIFIED'):'REFERENCE_ONLY';
  return{overall,validity,gates,baselineSummary,outcomes,xp,distance,waits,deaths,conditions,groupRanks,pairs,dominant};
}
function render(league,s){const m=league.metadata,c=league.configuration;const gateLabel=['INVALID','FAIL','NOT_QUALIFIED'].includes(s.overall)?'실패':['PASS','QUALIFIED'].includes(s.overall)?'통과':'부분';const reason=!s.validity?'실험 유효성 실패로 통계 결론 보류':c.smoke?'구조 검증 통과, 900틱 smoke라 720초 관문 미평가':c.experiment==='B'?'이동 비교 참고 결과, A 관문 미평가':c.experiment==='calibration'?`보정 적격 조건 ${s.overall==='QUALIFIED'?'충족':'미달'}`:`적용 관문 ${s.gates.filter(g=>g.applicable&&g.pass).length}/${s.gates.filter(g=>g.applicable).length} 통과`;return `관문: ${gateLabel} — ${m.distinctCaseCount}사례·${m.repeatCount}반복, ${reason}.\n변경: 사전 선언된 이동·위협·경험치 실험의 관측 결과.\n사용자 결정 필요: 결과 실패를 보존하며 후속 수치 변경은 별도 실험으로 진행한다.\n\n# S4b 결과\n\n${s.validity?'실험 구조 검증 통과.':'실험 유효성 실패: 통계 결론 보류.'} ${c.smoke?'900틱 smoke이며 720초 관문 결과가 아니다.':''}\n\n- 서로 다른 사례 ${m.distinctCaseCount}, 대응 seed 블록 ${m.seedBlockCount}, 결정론 반복 ${m.repeatCount}. 사례·반복을 독립 표본으로 합산하지 않았다.\n- 프로필 ${m.profileId}, source ${m.sourceCommit}, tuning SHA-256 ${m.experimentJson.tuningSha256}.\n- 원자료 CSV 해시는 source-manifest.csv에 있다. 통계는 열 개 CSV로 계산한다. raw/가 있으면 원본 JSON 해시를 추가 검증하고 CSV-only 재현은 기록된 원본 매니페스트를 신뢰한다.\n- XP 계수: ${JSON.stringify(m.experimentJson.experienceCurve)}. world unit: ${m.experimentJson.worldUnit}.\n\n|관문|적용|결과|\n|---|---|---|\n${s.gates.map(g=>`|${g.gate}|${g.applicable?'예':'아니오'}|${g.applicable?(g.pass?'PASS':'FAIL'):'NOT_EVALUATED'}|`).join('\n')}\n\n${c.smoke?`기준 random/C 기술 표본 ${s.baselineSummary.cases}사례: 실제 사망 ${s.baselineSummary.deaths}, 900틱까지 생존한 중도 종료 ${s.baselineSummary.truncatedAlive}. 720초 생존율·Wilson 구간·우세 정책 관문은 미평가다.`:`기준 random/C: ${s.baselineSummary.survived}/${s.baselineSummary.cases}, Wilson 95% [${s.baselineSummary.wilson95Low}, ${s.baselineSummary.wilson95High}]. ${c.experiment==='A'?`항상 공동1위 이상인 정책: ${s.dominant.join(', ')||'없음'}.`:'A의 우세 정책 관문은 이 모드에서 평가하지 않는다.'}`}\n\n## 해석과 재현\n\n거리 통계는 실제 표본의 sqrt(distanceSquared), 중앙값은 가운데 두 값 평균, p95는 nearest-rank다. 표본수·분포를 함께 기록하고 사망 후 좌표를 보간하지 않는다. 여러 시점은 독립 사람/seed 표본이 아니다. 익은 밭 대기에서 harvest만 완료 대기이고 destroyed는 경쟁 사건, death/duration은 우측 검열 하한이다. 검열 하한의 평균을 수확 완료 평균에 섞지 않는다.\n\nrank는 생존→도달틱→레벨→weaponDamage+toolActivationDamage+toolGrowthDamage+allyDamage다. 그룹 순위는 같은 seed수의 정수 합을 비교하므로 부동소수 허용오차로 공동1위를 늘리지 않는다. 식량·자재 stockpile은 점수가 아니다. B는 random 카드 정책의 이동 비교이며 A 관문과 합산하지 않는다.\n\n${['FAIL','INVALID','NOT_QUALIFIED'].includes(s.overall)?'## 원인 가설과 다음 실험\n\n1. 기준 생존율과 death-times.csv의 사망 시각 분포가 전역 위협 강도의 목표 적합성을 보여준다. 목표 밖이면 정책별 버프 대신 별도 전역 위협 후보를 사전 선언한다.\n2. group-ranks.csv와 xp-levels.csv는 순위가 생존·도달시간·레벨 중 어디서 갈리는지 구분한다. XP 실패는 관문 실패로 보존하고 다음 독립 실험에서 공유 곡선을 검토한다.\n3. movement-equality.csv와 mixed-random-pairs.csv가 통제·정책 구별의 근거다. 불일치 또는 동일 원장은 효과의 균형 결론보다 실험 유효성 문제를 먼저 조사한다.\n\n':''}모바일 조작·재미·첫 도구 이해도·메타 진행은 이 수치 실험으로 검증하지 않았다. 원본 S4 FAIL을 덮어쓰지 않는다.\n`;}
export async function report(input,output){const league=await load(input),s=summarize(league);await fs.mkdir(output,{recursive:true});const datasets={'gates':s.gates,'baseline': [s.baselineSummary],'outcomes':s.outcomes,'xp-levels':s.xp,'distance-distribution':s.distance,'ripe-wait-summary':s.waits,'death-times':s.deaths,'condition-ranks':s.conditions,'group-ranks':s.groupRanks,'mixed-random-pairs':s.pairs,'source-manifest':league.manifest};
  for(const[name,rows]of Object.entries(datasets)){const empty={ 'condition-ranks':['peopleRule','seed','cofirstPoliciesJson'],'group-ranks':['peopleRule','policy','caseCount','survived','ticksSum','levelSum','combatDamageSum','cofirst'],'mixed-random-pairs':['peopleRule','seed','identical','mixedChoices','randomChoices']};await fs.writeFile(path.join(output,name+'.csv'),formatCsv(rows.length?Object.keys(rows[0]):empty[name],rows));}
  await fs.writeFile(path.join(output,'report.md'),render(league,s));return s;
}
if(process.argv[1]&&pathToFileURL(path.resolve(process.argv[1])).href===import.meta.url){try{requireValue(process.argv.length===4,'usage: node tools/s4b-report.mjs INPUT OUTPUT');const result=await report(process.argv[2],process.argv[3]);console.log(`S4b report ${result.overall}`);if(!result.validity)process.exitCode=1;}catch(e){console.error(e.message);process.exitCode=1;}}
